
server:
  port: 8090
spring:
#  静态资源处理
#  resources:
#    cache:
#      cachecontrol:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.184.8
    post: 6379
#    //默认操作的库
#    database: 0
##    连接超时时间
#    timeout: 10000ms
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: 10000ms
##        最大空闲连接，默认为8
#        max-idle: 200
  rabbitmq:
    host: 192.168.184.9
    username: guest
    password: guest
    virtual-host: /
    port: 5672
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
#      //????
      pool-name: DateHikariCP
#      //???????
      minimum-idle: 5
#      //?????????????60000?10???
      idle-timeout: 100000
#      //????????10
      maximum-pool-size: 10
#      //?????????????
      auto-commit: true
#      ?????????0?????????1800000?30???
      max-lifetime: 180000
#      ?????????30000?30??
      connection-timeout: 30000
#      ????????????
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: